### ISSUE TITLE
Optimizing the crawler

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/rdfendpoints#18]
As it is the feed storage is highly inefficient and lead to errors:

```
Traceback (most recent call last): File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle result = handler(dict(self._environ), self._StartResponse) File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__ rv = self.router.dispatch(request, response) File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher return route.handler_adapter(request, response) File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__ return handler.dispatch() File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch return method(*args, **kwargs) File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/flankers/Scrawler.py", line 27, in get self.store_feeds() File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/flankers/Scrawler.py", line 78, in store_feeds i = WebResource.store_feed(entry) File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/datastore/models.py", line 216, in store_feed index.put() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3432, in _put return self._put_async(**ctx_options).get_result() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 326, in get_result self.check_success() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 321, in check_success self.wait() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 305, in wait if not ev.run1(): File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 235, in run1 delay = self.run0() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 224, in run0 callback(*args, **kwds) File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 455, in _on_rpc_completion result = rpc.get_result() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result return self.__get_result_hook(self) File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1881, in __put_hook self.check_rpc_success(rpc) File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1365, in check_rpc_success rpc.wait() File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 553, in wait if self.__rpc.state == apiproxy_rpc.RPC.RUNNING: DeadlineExceededError
```

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/flankers/Scrawler.py", line 27, in get
    self.store_feeds()
  File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/flankers/Scrawler.py", line 78, in store_feeds
    i = WebResource.store_feed(entry)
  File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/datastore/models.py", line 212, in store_feed
    labels = find_related_concepts(text)
  File "/base/data/home/apps/e~chronostriples/0-1.386873329962699293/flankers/textsemantics.py", line 46, in find_related_concepts
    print Exception('Cannot fetch taxonomy: ' + res + ' ' + str(e))
DeadlineExceededError
```

**Comment by mr-niels-christensen** [comment]
If you haven't already, it's usually useful to run the code with appstats on: https://cloud.google.com/appengine/docs/python/tools/appstats

**Comment by Mec-iS** [comment]
I have implemented the crawler with [this](https://github.com/mdornseif/gaetk_longtask).

Check the logs on the console.

**Comment by Mec-iS** [comment]
`DeadlineExceededError` again, but only after a minute of the task running.

**Comment by Mec-iS** [comment]
I divided the Scrawler in two cronjobs: [Scrawler](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/flankers/Scrawler.py#L17) (only store feeds) and [Indexing](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/flankers/indexing.py) (only index resource at certain time interval), the first to store the WebResource, the second that read the last store WebResource and populate the Indexer model.

Same error, more optimization needed.

**Comment by Mec-iS** [comment]
A good way to balance better the load on the crawler could be to make multiple smaller tasks for the different feed sources.

**Comment by Mec-iS** [comment]
Done
